### ISSUE TITLE
TypeError: key.indexOf is not a function

### ISSUE THREAD

**Issue by HichuYamichu** [malijs/mali#128]
**Describe the bug**
Mail throws an error when object instantiated from a class is passed to app.use().
```bash
TypeError: key.indexOf is not a function
    at Mali._getMatchingServiceName (G:\Projects\Other\examples\node_modules\mali\lib\app.js:476:13)
    at Mali.use (G:\Projects\Other\examples\node_modules\mali\lib\app.js:245:34)
    at main (G:\Projects\Other\examples\hello_world_dynamic\greeter_server.js:17:7)
    at Object.<anonymous> (G:\Projects\Other\examples\hello_world_dynamic\greeter_server.js:22:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
```

**To Reproduce**
```js
const path = require('path')
const Mali = require('mali')

const PROTO_PATH = path.resolve(__dirname, '../protos/helloworld.proto')
const HOSTPORT = '0.0.0.0:50051'

class RPCHandler {
  constructor() {
    this.sayHello = ctx => {
      ctx.res = { message: 'Hello ' + ctx.req.name }
    }
  }
}

function main () {
  const app = new Mali(PROTO_PATH, 'Greeter')
  app.use(new RPCHandler())
  app.start(HOSTPORT)
  console.log(`Greeter service running @ ${HOSTPORT}`)
}

main()
```

**Expected behavior**
Working app (this does work with regular grpc-node as shown below).
```js
const path = require('path');
const PROTO_PATH = path.resolve(__dirname, '../protos/helloworld.proto');

const grpc = require('grpc');
const protoLoader = require('@grpc/proto-loader');
const packageDefinition = protoLoader.loadSync(PROTO_PATH, {
  keepCase: true,
  longs: String,
  enums: String,
  defaults: true,
  oneofs: true
});
const hello_proto = grpc.loadPackageDefinition(packageDefinition).helloworld;

class RPCHandler {
  constructor() {
    this.sayHello = (call, callback) => {
      callback(null, { message: 'Hello ' + call.request.name });
    };
  }
}

function main() {
  const server = new grpc.Server();
  server.addService(hello_proto.Greeter.service, new RPCHandler());
  server.bind('0.0.0.0:50051', grpc.ServerCredentials.createInsecure());
  server.start();
}

main();
```

**Environment**
 - Version: ^0.19.0
 - Node.js version: v10.16.0
 - OS: Windows

**Comment by bojand** [comment]
Right now Mali does not support adding a full service like that. I actually did not know grpc supports this mechanism either; perhaps this is something newer. You need to specify the handler explicitly:

```js
const service = new RPCHandler()
app.use({ sayHello: service.sayHello })
```

**Comment by HichuYamichu** [comment]
Thanks for the quick reply. I guess I'll stick with explicit handler for now. Although I've found hacky workaround with:
```js
app.use(Object.assign({}, new RPCHandler()))
```

**Comment by anonrig** [comment]
We were checking for plain objects in `app.use()` but this was solved with the commit https://github.com/malijs/mali/commit/cdee479e1ee6095590c757db5f18a09e4a2d3598#diff-3546091c10d327e2474f4ca6d70663b3887a8971625cc06f3b1943b1bd34555dR222

If not, please open a new issue, and I'll be happy to address it. Thanks!
