### ISSUE TITLE
Getting Started example doesn't work

### ISSUE THREAD

**Issue by georgeben** [malijs/mali#260]
**Describe the bug**
I am following the example given in the [Getting started guide](https://mali.js.org/guide/getting_started.html), using the static approach for creating an application.

**To Reproduce**
- Use the example proto file provided:

```proto
syntax = "proto3";
package helloworld;

service Greeter {
  rpc SayHello (HelloRequest) returns (HelloReply) {}
  rpc SayHi (HelloRequest) returns (HelloReply) {}
}

message HelloRequest {
  string name = 1;
}

message HelloReply {
  string message = 1;
}
```
- Compile it and create a new application

```js
const services = require('./static/helloworld_grpc_pb')
const app = new Mali(services, 'GreeterService')
```

- Define the `sayHello` method and register it
```js
function sayHello (ctx) {
  ctx.res = { message: 'Hello ' + ctx.req.name }
}
app.use({ sayHello })

```

It throws the following error:
```
TypeError: Unknown method: sayHello
    at /Users/georgeben/Dev/grpc/mali-demo/node_modules/mali/lib/app.js:218:21
    at /Users/georgeben/Dev/grpc/mali-demo/node_modules/lodash.forown/index.js:161:11
    at baseForOwn (/Users/georgeben/Dev/grpc/mali-demo/node_modules/lodash.forown/index.js:122:20)
    at Object.forOwn (/Users/georgeben/Dev/grpc/mali-demo/node_modules/lodash.forown/index.js:447:20)
    at Mali.use (/Users/georgeben/Dev/grpc/mali-demo/node_modules/mali/lib/app.js:198:11)
    at Object.<anonymous> (/Users/georgeben/Dev/grpc/mali-demo/server.js:18:5)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
```

However, it works if I create an application like so:
```js
const app = new Mali(services, "Greeter") // Removing the "Service suffix"
```
**Expected behavior**
It should register a request handler

**Environment**
 - Version: 0.42.0
 - Node.js version: v14.16.1
 - OS: Mac OS Catalina

**Comment by anonrig** [comment]
Hi George, thank you for the issue. Can you open a pull request for this issue?

**Comment by georgeben** [comment]
Done https://github.com/malijs/malijs.github.io/pull/11

**Comment by anonrig** [comment]
Thanks George!
