### ISSUE TITLE
Updating to 0.43.0 and above breaks

### ISSUE THREAD

**Issue by chen572** [malijs/mali#263]
**Describe the bug**
When I update the service to use 0.43.0 or 0.43.1 it's breaking it (not starting up even)

The error ->
```
/node_modules/mali/lib/utils.js:10
  const name = Object.getPrototypeOf(call)?.constructor?.name ?? ''
                                           ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at Module.Hook._require.Module.require (/node_modules/require-in-the-middle/index.js:80:39)
    at Module.Hook._require.Module.require (/node_modules/require-in-the-middle/index.js:80:39)
    at Module.Hook._require.Module.require (/node_modules/require-in-the-middle/index.js:80:39)
    at Module.Hook._require.Module.require (/node_modules/require-in-the-middle/index.js:80:39)
```

Dependencies ->
```
    eslint: ^7.28.0,
    husky: ^6.0.0,
    jest: ^27.0.4,
    nodemon: ^2.0.7,
    pino-pretty: ^5.0.2,
    @grpc/grpc-js: ^1.3.2,
    @grpc/proto-loader: ^0.6.2,
    dotenv: ^10.0.0,
    lodash: ^4.17.21,
    mali: ^0.43.1,
    pino: ^6.11.3
```

**To Reproduce**
1. install the dependencies above
2. make a new grpc server and run it

**Environment**
 - Version: 0.43.0
 - Node.js version: 12.18.4
 - OS: mac os

**Comment by chen572** [comment]
Looks like the code is throwing the error cause it's expecting javascript there and not typescript features

**Comment by anonrig** [comment]
Hi chen, what's your node version?

**Comment by anonrig** [comment]
Hey Chen, Unfortunately we stopped supporting node 12, since it was EOL. Please upgrade to Node 14.
