### ISSUE TITLE
Error: write after end

### ISSUE THREAD

**Issue by stephen-dahl** [malijs/mali#51]
I have the following rpc
```
const { Transform } = require('stream');
const redis = require('../redis');

const flatten = new Transform({
	writableObjectMode: true,
	readableObjectMode: true,
	transform(keys, encoding, callback) {
		for (const key of keys) {
			this.push({ key });
		}
		callback();
	},
});

function scan(ctx) {
	ctx.res = redis.scanStream({ match: ctx.req.key }).pipe(flatten);
}

app.use('scan', scan);
```
After each request Mali logs 
```
  Error: write after end                                       app.js:303
      at writeAfterEnd (_stream_writable.js:236:12)
      at Transform.Writable.write (_stream_writable.js:287:5)
      at ScanStream.ondata (_stream_readable.js:639:20)
      at emitOne (events.js:116:13)
      at ScanStream.emit (events.js:211:7)
      at addChunk (_stream_readable.js:263:12)
      at readableAddChunk (_stream_readable.js:250:11)
      at ScanStream.Readable.push (_stream_readable.js:208:10)
      at opt.redis.(anonymous function) (c:\Users\steph\PhpstormProjects\redis-grpc\node_modules\ioredis\built\ScanStream.js:42:18)
      at tryCatcher (c:\Users\steph\PhpstormProjects\redis-grpc\node_modules\standard-as-callback\lib\utils.js:10:19)
```
My best guess is Mali is closing the network stream before my stream finishes.
Is this my fault or a Mali bug?

**Comment by bojand** [comment]
Hello, can you add more details please on what OS, version of node.js, and mali you are using. More context details on proto files or messages would be useful. I have created a simple [example](https://github.com/malijs/examples/tree/master/redis-chat) that seems to work fine. Both plain grpc and mali version of server are implemented.

Example server run 

```sh
node server_mali.js
RedisChat service running @ 0.0.0.0:50051
sending: foo:12
sending: foo:9
sending: foo:19
sending: foo:10
sending: foo:6
sending: foo:8
sending: foo:14
sending: foo:11
sending: foo:3
sending: foo:15
sending: foo:18
sending: foo:16
sending: foo:2
sending: foo:4
sending: foo:0
sending: foo:17
sending: foo:5
sending: foo:13
sending: foo:1
sending: foo:7
```
and client:
```sh
node client.js
{ key: 'foo:12' }
{ key: 'foo:9' }
{ key: 'foo:19' }
{ key: 'foo:10' }
{ key: 'foo:6' }
{ key: 'foo:8' }
{ key: 'foo:14' }
{ key: 'foo:11' }
{ key: 'foo:3' }
{ key: 'foo:15' }
{ key: 'foo:18' }
{ key: 'foo:16' }
{ key: 'foo:2' }
{ key: 'foo:4' }
{ key: 'foo:0' }
{ key: 'foo:17' }
{ key: 'foo:5' }
{ key: 'foo:13' }
{ key: 'foo:1' }
{ key: 'foo:7' }
count: 20
```

Same works with `server_grpc.js`

**Comment by stephen-dahl** [comment]
I can't find any meaningful difference between your example and what I have. In my own code, it went away when I wrapped my stream with Highland. I have my project working now, but it is interesting that it was not reproducible. I am going to chock it up to some strange interaction with my specific dependency graph and call it good.
